# This file is automatically generated by Rcpp::compileAttributes
# Do not edit manually

fast_batch_convolution_cpp <- function(signal, kernels, output_length) {
  .Call(`_fmriparametric_fast_batch_convolution_cpp`, signal, kernels, output_length)
}


