name: Windows CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  R-CMD-check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
      - name: Check
        run: |
          R CMD build .
          R CMD check *.tar.gz --no-manual --no-build-vignettes
